config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root "quotes#index"
  get "/favourite_quotes", to: "favourites#favourite_quotes"
  resources :quotes do
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :quotes, only: [:create]
      resources :people, only: [:create]
    end
  end
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  validates :user, presence: true
  validates :quote, presence: true, uniqueness: { scope: :user }

  belongs_to :user
  belongs_to :quote
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :slack_name, uniqueness: true, format: { with: /@.*/i, on: :save }, if: :slack_name
  validates :full_name, presence: true, unless: :slack_name
  has_many :quotes, dependent: :destroy

  def preferred_name
    full_name || slack_name
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :body, presence: true
  validates :person_id, presence: true

  belongs_to :created_by, class_name: :User, foreign_key: "user_id"
  belongs_to :person

  has_many :votes, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  def score
    votes.sum(:value)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise(
    :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  )
  has_many :quotes
  has_many :votes, dependent: :destroy

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.find_by(email: data["email"])

    unless user
      user = User.create(
        email: data["email"],
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  has_many :favourites, dependent: :destroy
  has_many :favourite_quotes, through: :favourites, source: :quote
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  enum value: { hate_it: -2, dislike_it: -1, like_it: 1, love_it: 2 }

  validates :value, presence: true
  validates :user, uniqueness: { scope: :quote }

  belongs_to :user
  belongs_to :quote
end

app/controllers/api/v1/people_controller.rb
class Api::V1::PeopleController < ActionController::Base

  def create
    @person = Person.new person_params
    if @person.save
      render :show, status: :created, format: :json
    else
      render json: { message: @person.errors }, status: 400
    end
  end

  private

  def person_params
    params.require(:person).permit(:slack_name, :full_name)
  end
end

app/controllers/api/v1/quotes_controller.rb
class Api::V1::QuotesController < ActionController::Base

  def create
    @quote = Quote.new quote_params
    if @quote.save
      render :show, status: :created, format: :json
    else
      render json: { message: @quote.errors }, status: 400
    end
  end

  private

  def quote_params
    raw_params.merge(person: quoted_person)
  end

  def raw_params
    params.require(:quote).permit(:body, :location, :quoted_person)
  end

  def quoted_person
    return unless raw_params[:quoted_person]
    person = raw_params[:quoted_person]
    if person.start_with?('@')
      Person.find_or_create_by(slack_name: person)
    else
      Person.find_or_create_by(full_name: person)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :vote_types

  def vote_types
    [["I hate it", :hate_it],
     ["I'm against it", :against_it],
     ["I like it", :like_it],
     ["I love it", :love_it]
    ]
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!

  def create
    favourite = current_user.favourites.new quote: current_quote
    if favourite.save
      flash[:notice] = "Favourited!"
    else
      flash[:alert] = "Failed to favourite.  Had you already favourited?"
    end
    redirect_to quotes_path
  end

  def destroy
    favourite = current_user.favourites.find params[:id]
    favourite.destroy
    redirect_to quotes_path, notice: "Favourite removed."
  end

  def favourite_quotes
    @user_favourites = current_user.favourite_quotes
    @user_votes = current_user.votes
  end

  private

  def current_quote
    Quote.find params[:quote_id]
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!

  def show
    @quote = Quote.find params[:id]
    @vote = @quote.votes.find_by(user: current_user)
    @user_votes = current_user.votes
    @user_favourites = current_user.favourite_quotes
  end

  def edit
    @quote = current_user.quotes.find params[:id]
  end

  def update
    @quote = current_user.quotes.find params[:id]
    if @quote.update quote_params
      redirect_to @quote
    else
      render :edit
    end
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new quote_params
    @quote.created_by = current_user
    if @quote.save
      redirect_to @quote
    else
      render :new
    end
  end

  def index
    @quotes = Quote.order(created_at: :desc)
    @user_votes = current_user.votes
    @user_favourites = current_user.favourite_quotes
  end

  def destroy
    @quote = current_user.quotes.find params[:id]
    @quote.destroy
    redirect_to quotes_path
  end

  private

  def quote_params
    raw_params.merge(person: quoted_person)
  end

  def raw_params
    params.require(:quote).permit(:body, :location, :quoted_person)
  end

  def quoted_person
    return unless raw_params[:quoted_person]
    person = raw_params[:quoted_person]
    if person.start_with?('@')
      Person.find_or_create_by(slack_name: person)
    else
      Person.find_or_create_by(full_name: person)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    vote = current_quote.votes.new vote_params.merge(user: current_user)
    if vote.save
      flash[:notice] = "Voted!"
    else
      flash[:alert] = "Vote failed to create.  Had you already voted?"
    end
    redirect_to quotes_path
  end

  def update
    vote = current_quote.votes.find_by!(user: current_user)
    vote.update vote_params
    redirect_to quotes_path, notice: "Vote updated" # error thrown if update fails
  end

  def destroy
    @vote = current_user.votes.find params[:id]
    flash[:notice] = "Vote deleted" if @vote.destroy
    redirect_to quotes_path
  end

  private

  def vote_params
    params.require(:vote).permit(:value)
  end

  def current_quote
    Quote.find params[:quote_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/favourites/favourite_quotes.html.erb
<% @user_favourites.each do |quote| %>
  <div class="well">
    <%= render quote %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://stembolt.com">Stembolt</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user && current_user.favourite_quotes.any? %>
        <li><%= link_to "Favourite Quotes", favourite_quotes_path %></li>
      <% end %>
      <li><%= link_to "All Quotes", root_path %></li>
      <li><%= link_to "Add a Quote", new_quote_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="navbar-container">
        <% if current_user %>
          <%= render "layouts/navbar" %>
        <% end %>
      </div>
      <% if alert %>
        <div class="well alert-danger">
          <%= alert %>
        </div>
      <% end %>
      <% if notice %>
        <div class="well alert-success">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/quotes/_form.html.erb
<% if @quote.errors.any? %>
  <% @quote.errors.each do |msg| %>
    <%= msg == :person_id ? 'Enter a quoted person' : msg %>
  <% end %>
<% end %>
<%= simple_form_for @quote do |f| %>
  <%= f.input :quoted_person %>
  <%= f.input :body %>
  <%= f.input :location %>
  Please format as shown below:
  <div class="quote-example">
    <span>Quoted Person</span> said, <q>body</q>, <span>location</span>.
  </div>
  <%= f.submit "Submit Quote" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= quote.person.preferred_name %> said, <q><%= quote.body %></q>, <%= quote.location %>.
<% if quote.created_by == current_user %>
  <%= link_to "delete quote", quote_path(quote), method: :delete, data: { confirm: "Delete quote?" } %>
  <%= link_to "edit quote", edit_quote_path(quote) %>
<% end %>
<% if @user_favourites.include? quote %>
  <%= link_to "Unfavourite quote", quote_favourite_path(
    quote,
    quote.favourites.find_by(user: current_user)
  ),
  method: :delete %>
<% else %>
  <%= link_to "Favourite quote", quote_favourites_path(quote), method: :post %>
<% end %>
<%=
  render 'votes/voting',
  quote: quote,
  vote: quote.votes.find_by(user: current_user)
%>
<div>
  Quote Love: <%= quote.score %>
</div>

app/views/quotes/_quote_list.html.erb
<% quotes.each do |quote|  %>
  <div class="well">
    <%= link_to "->", quote %>
    <%= render quote %>
  </div>
<% end %>

app/views/quotes/best.html.erb
<%= render "quote_list", quotes: @quotes %>

app/views/quotes/edit.html.erb
<%= render "form" %>

app/views/quotes/error.html.erb
<p>Error:  No quote found in the database for that ID.</p>

app/views/quotes/index.html.erb
<%= render "quote_list", quotes: @quotes %>

app/views/quotes/new.html.erb
<%= render 'form' %>

app/views/quotes/show.html.erb
<%= render @quote, vote: @vote %>

app/views/votes/_voting.html.erb
<% if @user_votes.include? vote %>
  <% Vote.values.keys.each do |opinion| %>
    <%= link_to t(opinion, scope: :votes), quote_vote_path(quote, vote, { vote: { value: opinion } }), method: :patch %>
  <% end %>
  <%= link_to "Erase my vote", quote_vote_path(quote, vote), method: :delete %>
<% else %>
  <% Vote.values.keys.each do |opinion| %>
    <%= link_to t(opinion, scope: :votes), quote_votes_path(quote, { vote: { value: opinion } }), method: :post %>
  <% end %>
<% end %>